global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'login-chat'
    static_configs:
      - targets: ['login-chat-server:7001']

  - job_name: 'chat-rest-server'
    static_configs:
      - targets: ['chat-rest-server:7002']

  - job_name: 'socket-server'
    static_configs:
      - targets: ['socket-chat:7003']
